New functionality for improved manipulation of rowData
rformassspectrometry/QFeatures pull request #134
Opened 2021-06-02 16:41 UTC by cvanderaa

This PR adds two new functions (taken from `SCP.replication`): 
- `getRowData` extracts the `rowData` from one or more assays in a `QFeatures` object. The output is a single `DFrame` table that contains the `rowData` for all selected assays.
- `setRowData` function modifies columns in the `rowData` from one or more assays in `QFeatures` object. This function can also be used to remove columns in the `rowData`.

I have updated the documentation and added some unit tests. I also added a new section (*Accessors*) in the `QFeatures.Rmd` section that explicits the usage of the accessor functions. I would like to have a review of this new section.

The points that I think need attention or that remain to be done: 

- [ ] Do we agree on the function names?
- [ ] Review the new section in the vignette
- [ ] Update the `NEWS.md` file

This PR is supposed to close [this issue](https://github.com/UCLouvain-CBIO/SCP.replication/issues/6) in `SCP.replication`

2021-06-03 08:18 UTC, cvanderaa commented
The PR faces some errors that I don't have locally, probably because I still need to update R and Bioconductor on my computer. I'll fix that asap!

2021-06-11 08:07 UTC, lgatto commented
See discussion notes.

2021-06-12 16:40 UTC, lgatto requested changes

2021-06-12 16:40 UTC, lgatto commented on vignettes/QFeatures.Rmd
> +object. Therefore there are as many `rowData` tables as numbers of
Therefore there are as many `rowData` tables as there are assays.

2021-06-12 16:40 UTC, lgatto commented on vignettes/QFeatures.Rmd
> +to replace and the elements of the `List` contain a `DataFrame` with
the assays to be updated

2021-06-12 16:40 UTC, lgatto commented on vignettes/QFeatures.Rmd
> +to replace and the elements of the `List` contain a `DataFrame` with
contain `DataFrame`s with

2021-06-12 16:40 UTC, lgatto commented on vignettes/QFeatures.Rmd
> +See here that the new variables are added to the `rowData` of the
As shown below, the new `mean` and `sd` variables have been added to ...

2021-06-12 16:40 UTC, lgatto commented on vignettes/QFeatures.Rmd
> +suppose we want to visualize the quantititation data (present in the
quantitative data or quantitation data

2021-06-13 07:40 UTC, lgatto commented
@cvanderaa  Could you also update the NEWS file

2021-06-13 08:59 UTC, lgatto commented
I don't get what is happening in the action and why it fails. It looks like it's related to the methods package that somehow fails to find a method.

2021-06-14 12:26 UTC, cvanderaa commented
I inserted your suggestions and adapted the NEWS file. I also bumped the version. If we can ignore the GHA issue, I'm ready for the merge.

2021-06-22 11:11 UTC, merged