Improved validity checks and solve subsetting issue
rformassspectrometry/QFeatures pull request #139
Opened 2021-06-30 16:14 UTC by cvanderaa

In an attempt to solve https://github.com/UCLouvain-CBIO/SCP.replication/issues/8, I realized that the validity checks on `AssayLinks` could be improved. I refactor the checks, put them in a separate file, and added unit tests. 

The unit tests for `filterFeatures` currently fails because it now detects an overlooked bug during subsetting. I'm working on it so **don't merge yet**. I still need to: 
- [x] Improve validity checks
- [ ] Debug the unit tests for `filterFeatures`
- [ ] Make sure that this solves https://github.com/UCLouvain-CBIO/SCP.replication/issues/8

2021-07-01 17:02 UTC, cvanderaa commented
I finished the PR, but there seems to be an issue that I cannot reproduce locally, even with the latest packages...

2021-07-02 07:26 UTC, lgatto commented
It looks like this is the same error that we currently have in `MSnbase` (see [here](https://github.com/lgatto/MSnbase/runs/2969471507?check_suite_focus=true#step:12:32)):
```
attempt to set 'rownames' on an object with no dimensions
```

Ping @jorainer @sgibb in case you have an idea.

2021-07-02 07:35 UTC, lgatto requested changes

2021-07-02 07:35 UTC, lgatto commented on DESCRIPTION
> +Version: 1.3.4
The version should stay 1.3.3, which corresponds to updates specific to github development, that will be pushed to Bioc devel (currently at 1.3.2).

2021-07-02 07:35 UTC, lgatto commented on NEWS.md
> +## QFeatures 1.3.4
See above.

2021-07-02 08:34 UTC, cvanderaa commented
> It looks like this is the same error that we currently have in `MSnbase` (see [here](https://github.com/lgatto/MSnbase/runs/2969471507?check_suite_focus=true#step:12:32)):
> 
> ```
> attempt to set 'rownames' on an object with no dimensions
> ```
> 
> Ping @jorainer @sgibb in case you have an idea.

In both cases (`MSnbase` and `QFeatures`), the error appears during normalization.

2021-07-02 09:08 UTC, cvanderaa commented
Ah wait, I am able to reproduce the error locally using the GitHub version of `MsCoreUtils`!

2021-07-02 09:32 UTC, cvanderaa commented
The issue lies in `preprocessCore`, the `normalize.quantiles.robust` function is not behaving as expected. See this example:
```r
library(QFeatures)
library(preprocessCore)
data(hlpsms)
fts <- readQFeatures(hlpsms, ecol = 1:10, name = "psms")
se <- fts[[1]]
normalize.quantiles(assay(se))
## returns a 3010 by 10 matrix (as expected)
normalize.quantiles.robust(assay(se))
## returns NULL
```

2021-07-02 10:04 UTC, lgatto commented
could you post on issue on the MsCoreUtils repo, please.

2021-07-02 12:24 UTC, lgatto commented
Note that [MSnbase](http://bioconductor.org/checkResults/devel/bioc-LATEST/MSnbase/nebbiolo2-buildsrc.html) also fails on Bioconductor because of this.

2021-07-02 12:53 UTC, lgatto commented
See [here](https://github.com/bmbolstad/preprocessCore/pull/15) for the source of the error and a fix.

2021-07-03 10:25 UTC, cvanderaa commented
The PR now passes the checks, in my opinion it is ready for merge. When merging, would it be possible to push to Bioconductor? That would allow me to use the recent changes to solve the issues in `SCP.replication`.

2021-07-03 12:13 UTC, merged

2021-07-03 12:15 UTC, lgatto commented
Pushed to Bioc.