feat+docs: add readSummarizedExperiment
rformassspectrometry/QFeatures pull request #45
Opened 2020-02-05 12:16 UTC by cvanderaa

Split readFeatures into 2 separate functions. readSummarizedExperiment is called within readFeatures. The documentation is adapted to include both functions in the same help page.

2020-02-05 13:18 UTC, lgatto requested changes

2020-02-05 13:18 UTC, lgatto commented on R/Features-constructors.R
> +##' @usage
Don't hard-code the usage section here - it will be generated automatically by roxygen in the final Rd file.

2020-02-05 13:18 UTC, lgatto commented on R/Features-constructors.R
> +##' @aliases readFeatures
If the man page is about `readFeatures`, then you need to add `readSummarizedExperiment` as an alias. Otherwise it's ok.

2020-02-05 13:18 UTC, lgatto commented on R/Features-constructors.R
>      se <- SummarizedExperiment(assay,
No need to create `se` to then return it right away. Just use the call to the constructor as last expression.

2020-02-05 16:14 UTC, cvanderaa commented
Thanks a lot for the review ! Here are some updates and additional test units !

2020-02-06 06:59 UTC, lgatto commented
Could you also add yourself as a contributor (`role = "ctb"`) to the DESCRIPTION file.

2020-02-06 08:11 UTC, cvanderaa commented
Thanks for including me in the package development!

2020-02-06 23:00 UTC, lgatto approved these changes

2020-02-06 23:00 UTC, lgatto commented on tests/testthat/test_readFeatures.R
> +test_that("readFeatures", {
This unit test should be called `readSummarizedExperiment`.

2020-02-06 23:00 UTC, merged